config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get    '/users/:id', to: 'users#show', as: 'user'
  get    '/signup',    to: 'users#new'
  post   '/signup',    to: 'users#create'

  resources :events, only: [:new, :create, :show, :index]

  resources :attendances, only: [:create, :destroy]

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :attendances
  has_many :attendees, through: :attendances, source: :user

  scope :past, -> { where('time < ?', Time.now) }
  scope :upcoming, ->  { where('time > ?', Time.now) }
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  # Associations
  has_many :created_events, class_name: 'Event', foreign_key: 'creator_id'
  has_many :attendances
  has_many :events, through: :attendances

  # Validations
  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Callbacks
  before_save :downcase_email

  # Remembers the user in the database, for use in persistent sessions
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Forget a user
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if rememeber token matches digest
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Encrypts given token for use in digest
  def User.digest
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(token, cost: cost)
  end

  # Generates a new, random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  private

    def downcase_email
      email.downcase!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

    # Confirms a logged-in user
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def create
    @event = Event.find(attendance_params[:event_id])
    @event.attendances.create(user_id: current_user.id)
    redirect_to event_url(@event)
  end

  def destroy
    @attendance = Attendance.find(params[:id])
    current_user.attendances.destroy(@attendance)
    redirect_to(:back)
  end

  private
    def attendance_params
      params.require(:attendance).permit(:event_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      flash[:success] = "Event created."
      redirect_to events_url
    else
      flash.now[:danger] = "Event did not save."
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  private

    def event_params
      params.require(:event).permit(:title, :description, :location, :time)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      flash[:success] = 'Logged in.'
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email/password combination.'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User created."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, 
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # returns the full page title on a per-page basis
  def full_title(page_title = '')
    base_title = "Private Events"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end

  # Returns the current, logged-in user (if any)
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Remembers the user with a persistent session
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.rememeber_token
  end

  # Forgets persistent user session
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs user out
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h3>All Events</h3>
<table>
  <tr>
    <th>Title</th>
    <th>Location</th>
    <th>Time</th>
    <th>Creator</th>
  </tr>
  <% @events.each do |event| %>
    <tr>
      <td><%= link_to event.title, event_url(event) %></td>
      <td><%= event.location %></td>
      <td><%= event.time %></td>
      <td><%= link_to event.creator.name, user_url(event.creator) %></td>
    </tr>
  <%  end %>
</table>

app/views/events/new.html.erb
<% provide(:title, "New event") %>
<p>
  <%= form_for(@event) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :description %>
    <%= f.text_field :description %>

    <%= f.label :location %>
    <%= f.text_field :location %>

    <%= f.label :time %>
    <%= f.datetime_local_field :time %>

    <%= f.submit "Create new event" %>
  <% end %>
</p>

app/views/events/show.html.erb
<h3><%= @event.title %></h3>
<p><%= @event.description %></p>
<span>
  <em>
    By? <%= link_to @event.creator.name, user_url(@event.creator) %>
    Where? <strong><%= @event.location %></strong> 
    When? <strong><%= @event.time %></strong>
  </em>
</span>

<h4>Attendees:</h4>
<% if @event.attendees.any? %>
  <% @event.attendees.each do |attendee| %>
    <p><%= link_to attendee.name, user_url(attendee) %></p>
  <% end %>
<% else %>
  <span>No attendees!</span>
<% end %>


<% if logged_in? && (current_user != @event.creator) %>
  <h4>Would you like to attend?</h4>
  <% if @event.time < Time.now %>
    <p>(This event is over.)</p>
  <% elsif @event.attendees.include?(current_user) %>
    <%= form_for(current_user.attendances.find_by(event_id: @event.id), 
                                          method: :delete) do |f| %>
      <%= f.submit "Leave event" %>
    <% end %>
  <% else %>
    <%= form_for(current_user.attendances.build(event_id: @event.id)) do |f| %>
      <%= f.hidden_field :event_id, value: @event.id %>
      <%= f.submit "Attend event" %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1><%= link_to "Private Events", root_url %></h1>
      <% if logged_in? %>
        <span>Welcome, <em><%= link_to current_user.name, user_url(current_user) %>.</em></span>
      <% end %>
      <ul>
        <li><%= link_to "View all events", events_path %></li>
        <% if logged_in? %>
          <li><%= link_to "New event", new_event_path %></li>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign up", signup_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </header>

    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div>
    <div>
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<p>This is a handsome home-page.</p>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1>Sign up</h1>
<p>
  <%= form_for(@user, url: signup_path) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Sign up" %>
  <% end %>
</p>

app/views/users/show.html.erb
<h3><%= @user.name %>'s Hosting:</h3>
<table>
  <tr>
    <th>Title</th>
    <th>Time</th>
  </tr>
  <% if @user.created_events.any?
      @user.created_events.each do |event| %>
        <tr>
          <td><%= link_to event.title, event_url(event)%></td>
          <td><%= event.time %></td>
        </tr>
  <%  end
    else %>
    <tr>
      <td>No hosted events found!</td>
    </tr>
  <% end %>
</table>

<% if @user.events.any? %>
<h3>Previously Attended Events:</h3>
<table>
  <tr>
    <th>Title</th>
    <th>Time</th>
  </tr>
  <% @user.events.past.each do |event| %>
    <tr>
      <td><%= link_to event.title, event_url(event)%></td>
      <td><%= event.time %></td>
    </tr>
  <%  end %>
</table>

<h3>Upcoming Events:</h3>
<table>
  <tr>
    <th>Title</th>
    <th>Time</th>
  </tr>
  <% @user.events.upcoming.each do |event| %>
    <tr>
      <td><%= link_to event.title, event_url(event)%></td>
      <td><%= event.time %></td>
    </tr>
  <%  end %>
</table>
<% end %>